name: bs-detector
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pandas>=2.2
  - numpy
  - pyarrow
  - pip
  # GPU stack
  - pytorch        # gets the matching torch build
  - pytorch-cuda=12.1  # CUDA runtime; needs the nvidia channel above
  - pip:
      - kagglehub
      - transformers>=4.43
      - accelerate>=0.33

